### ISSUE TITLE
how to implement multi-step tool use "without" Langchain?

### ISSUE THREAD

**Issue by kun432** [cohere-ai/notebooks#152]
trying multi-step tool use notebook, it seems multi-step tool use depends on LangChain's Agent ability.

want to know how to  implement with Cohere's Python SDK or API, not with Langchain.

**Comment by BeatrixCohere** [comment]
Hi, thanks for trying out multi-step with cohere. It was first introduced into langchain as an experimental mode, instructions for how to implement with the API&SDK coming soon 🙂

**Comment by BeatrixCohere** [comment]
Hi, this is now public and the [docs are here](https://docs.cohere.com/docs/multi-step-tool-use). Please reopen an issue / post on the [community discord ](https://discord.com/invite/co-mmunity) if you face any issues with it.

**Comment by kun432** [comment]
@BeatrixCohere

works confirmed! Thanks!
